### ISSUE TITLE
Usar separador de linha de acordo com o sistema operacional

### ISSUE THREAD

**Issue by manoelcampos** [trasherdave/exportador-produto-csv#1]
Só uma dica que não mencionei e nem mostrei nos vídeos.
`\n` é o separador de linha usado no linux e macOS é `\n\r`. No windows é apenas `\n`.
Assim, no lugar de usar qualquer um desses caracteres diretamente, pode-se usar `System.lineseparator()`.
Assim, a aplicação vai verificar qual o OS e usar o separador correto.

https://github.com/trasherdave/exportador-produto-csv/blob/9f59b7f9fb55f2efdf2bb42982c59bf09b9059e2/src/main/java/com/david/exportador/produto/csv/ExportadorListaProdutoCSV.java#L17

**Comment by trasherdave** [comment]
Ótima dica! obrigado!
